controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz, matches controlPeriod of 0.001s
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    position_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - FL_hip_joint
        - FL_thigh_joint
        - FL_calf_joint
        - FR_hip_joint
        - FR_thigh_joint
        - FR_calf_joint
        - RL_hip_joint
        - RL_thigh_joint
        - RL_calf_joint
        - RR_hip_joint
        - RR_thigh_joint
        - RR_calf_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
        - effort
      gains:
        FL_hip_joint: { p: 100.0, i: 0.1, d: 10.0 }
        FL_thigh_joint: { p: 100.0, i: 0.1, d: 10.0 }
        FL_calf_joint: { p: 100.0, i: 0.1, d: 10.0 }
        FR_hip_joint: { p: 100.0, i: 0.1, d: 10.0 }
        FR_thigh_joint: { p: 100.0, i: 0.1, d: 10.0 }
        FR_calf_joint: { p: 100.0, i: 0.1, d: 10.0 }
        RL_hip_joint: { p: 100.0, i: 0.1, d: 10.0 }
        RL_thigh_joint: { p: 100.0, i: 0.1, d: 10.0 }
        RL_calf_joint: { p: 100.0, i: 0.1, d: 10.0 }
        RR_hip_joint: { p: 100.0, i: 0.1, d: 10.0 }
        RR_thigh_joint: { p: 100.0, i: 0.1, d: 10.0 }
        RR_calf_joint: { p: 100.0, i: 0.1, d: 10.0 }