controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    go2_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - FL_hip_joint
        - FL_thigh_joint
        - FL_calf_joint
        - FR_hip_joint
        - FR_thigh_joint
        - FR_calf_joint
        - RL_hip_joint
        - RL_thigh_joint
        - RL_calf_joint
        - RR_hip_joint
        - RR_thigh_joint
        - RR_calf_joint

      command_interfaces:
        - position

      state_interfaces:
        - position
        - velocity
        - effort

      state_publish_rate: 100.0  # Hz
      action_monitor_rate: 20.0  # Hz

      allow_partial_joints_goal: false
      constraints:
        stopped_position_threshold: 0.01
        goal_time: 0.0
